TARGET_EXEC := ailib_bench_linux

CC := riscv64-unknown-linux-gnu-gcc
CXX := riscv64-unknown-linux-gnu-g++

CORE_ARCH_ABI := -march=rv64imafdcv_zfh_zvfh -mabi=lp64d

BUILD_DIR := ./build_linux
SRC_DIRS := ./src ./test

SRCS := $(sort $(shell find $(SRC_DIRS) -name '*.cpp' -or -name '*.c' -or -name '*.s'))
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

INC_DIRS := $(shell find $(SRC_DIRS) -type d) inc/
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

COMMON_FLAGS := -fno-tree-vectorize \
                -fno-tree-loop-vectorize \
                -fno-tree-slp-vectorize \
                -Wall -Wextra -MMD -MP -ffunction-sections -fdata-sections \
                -O3

CFLAGS := $(CORE_ARCH_ABI) $(INC_FLAGS) $(COMMON_FLAGS)
CPPFLAGS := $(CORE_ARCH_ABI) $(INC_FLAGS) $(COMMON_FLAGS)
LDFLAGS := $(CORE_ARCH_ABI) -Wl,--gc-sections -static

$(BUILD_DIR)/$(TARGET_EXEC): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.c.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.cpp.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@


.PHONY: clean
clean:
	-rm -r $(BUILD_DIR)

-include $(DEPS)
